// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: social_feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSocialFeedFollow = `-- name: CreateSocialFeedFollow :one
INSERT INTO social_feed_followed (id, user_id, social_feed_id, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, social_feed_id, created_at, updated_at
`

type CreateSocialFeedFollowParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	SocialFeedID uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateSocialFeedFollow(ctx context.Context, arg CreateSocialFeedFollowParams) (SocialFeedFollowed, error) {
	row := q.db.QueryRowContext(ctx, createSocialFeedFollow,
		arg.ID,
		arg.UserID,
		arg.SocialFeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SocialFeedFollowed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SocialFeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
